### ISSUE TITLE
generating a full configuration file results in ModuleNotFoundError

### ISSUE THREAD

**Issue by gerdesj** [mickem/nscp#1012]
I am attempting to generate a full nsclient.ini, which results in an error:

```
C:\Program Files\NSClient++>nscp settings --generate --add-defaults --load-all
L   settings Creating new settings file: ini://${shared-path}/nsclient.ini
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = 'python'
  isolated = 0
  environment = 1
  user site = 1
  safe_path = 0
  import site = 1
  is in build tree = 0
  stdlib dir = 'C:\Program Files\NSClient++\Lib'
  sys._base_executable = 'C:\\Program Files\\NSClient++\\nscp.exe'
  sys.base_prefix = 'C:\\Program Files\\NSClient++'
  sys.base_exec_prefix = 'C:\\Program Files\\NSClient++'
  sys.platlibdir = 'DLLs'
  sys.executable = 'C:\\Program Files\\NSClient++\\nscp.exe'
  sys.prefix = 'C:\\Program Files\\NSClient++'
  sys.exec_prefix = 'C:\\Program Files\\NSClient++'
  sys.path = [
    'C:\\Program Files\\NSClient++\\python311.zip',
    'C:\\Program Files\\NSClient++',
    'C:\\Program Files\\NSClient++\\Lib',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x000024c8 (most recent call first):
  <no Python frame>

C:\Program Files\NSClient++>

```
This is on a new Windows server 2025 VMware VM, patched to date.

**Comment by gerdesj** [comment]
I tried removing my current nsclient.ini out of the way and I've also tried with the stock nsclient.ini from installation.  I did a simple install from the .msi.

The out of the box .ini file has lots of  _; Undocumented key_  - as mentioned in another issue hereabouts.

I'll move this over to a test box and try and narrow it down - playing on a DC isn't a good look!

**Comment by mickem** [comment]
Should be fixed here: https://github.com/mickem/nscp/releases/tag/0.9.13 If not please reopen.

**Comment by leffu33** [comment]
So I try to generate all available settings in custom.ini to verify few options. And I get same error as above. \
I update 0.9.12 to 0.9.13.
Restart system after it. and get in powershell:
```powershell
PS C:\Program Files\NSClient++> .\nscp.exe --version
NSClient++, Version: 0.9.13 2025-08-11, Platform: x64
PS C:\Program Files\NSClient++> .\nscp.exe settings --generate --add-defaults --load-all
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = 'python'
  isolated = 0
  environment = 1
  user site = 1
  safe_path = 0
  import site = 1
  is in build tree = 0
  stdlib dir = 'C:\Program Files\NSClient++\Lib'
  sys._base_executable = 'C:\\Program Files\\NSClient++\\nscp.exe'
  sys.base_prefix = 'C:\\Program Files\\NSClient++'
  sys.base_exec_prefix = 'C:\\Program Files\\NSClient++'
  sys.platlibdir = 'DLLs'
  sys.executable = 'C:\\Program Files\\NSClient++\\nscp.exe'
  sys.prefix = 'C:\\Program Files\\NSClient++'
  sys.exec_prefix = 'C:\\Program Files\\NSClient++'
  sys.path = [
    'C:\\Program Files\\NSClient++\\python311.zip',
    'C:\\Program Files\\NSClient++',
    'C:\\Program Files\\NSClient++\\Lib',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x000007c0 (most recent call first):
  <no Python frame>
PS C:\Program Files\NSClient++> .\nscp.exe settings --activate-module PythonScript --add-defaults
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = 'python'
  isolated = 0
  environment = 1
  user site = 1
  safe_path = 0
  import site = 1
  is in build tree = 0
  stdlib dir = 'C:\Program Files\NSClient++\Lib'
  sys._base_executable = 'C:\\Program Files\\NSClient++\\nscp.exe'
  sys.base_prefix = 'C:\\Program Files\\NSClient++'
  sys.base_exec_prefix = 'C:\\Program Files\\NSClient++'
  sys.platlibdir = 'DLLs'
  sys.executable = 'C:\\Program Files\\NSClient++\\nscp.exe'
  sys.prefix = 'C:\\Program Files\\NSClient++'
  sys.exec_prefix = 'C:\\Program Files\\NSClient++'
  sys.path = [
    'C:\\Program Files\\NSClient++\\python311.zip',
    'C:\\Program Files\\NSClient++',
    'C:\\Program Files\\NSClient++\\Lib',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00001d00 (most recent call first):
  <no Python frame>
PS C:\Program Files\NSClient++>
```

So the problem described by @gerdesj still exist

**Comment by mickem** [comment]
I am so sorry, I only fixed the script and tested locally, I see now in the pipeline build it is still missing...

**Comment by mickem** [comment]
Another attempt at fixing this: https://github.com/mickem/nscp/releases/tag/0.9.14
